distinct history_schemas.identifier as identifier,
reqNoEdit.method    AS request_method,
reqNoEdit.path      AS request_path,
reqNoEdit.proto     AS request_proto,
reqNoEdit.host      AS request_host,
reqNoEdit.header    AS request_headers,
reqNoEdit.param     AS request_param,
reqEdit.method      AS request_edit_method,
reqEdit.path        AS request_edit_path,
reqEdit.proto       AS request_edit_proto,
reqEdit.host        AS request_edit_host,
reqEdit.header      AS request_edit_headers,
reqEdit.param       AS request_edit_param,
resA.header 		AS response_headers,
body